// Generated by scripts/generate-error-codes.mjs — do not edit by hand.
// Source: loash-industries/trinary-exchange @ packages/triex/sources, packages/token/sources
// Regenerate: npm run generate:error-codes

/** Every abort constant declared by the contracts, as `module::EConstantName`. */
export type MoveAbortName =
  | 'book::EInvalidAmountIn'
  | 'book::EEmptyOrderbook'
  | 'book::EInvalidPriceRange'
  | 'book::EInvalidTicks'
  | 'book::ENewQuantityMustBeLessThanOriginal'
  | 'book::EBookOrderNotFound'
  | 'order::EInvalidNewQuantity'
  | 'order::EOrderExpired'
  | 'order_info::EOrderInvalidPrice'
  | 'order_info::EInvalidExpireTimestamp'
  | 'order_info::EInvalidOrderType'
  | 'order_info::EPOSTOrderCrossesOrderbook'
  | 'order_info::EFOKOrderCannotBeFullyFilled'
  | 'order_info::EMarketOrderCannotBePostOnly'
  | 'order_info::ESelfMatchingCancelTaker'
  | 'fee_policy::EClassAlreadyExists'
  | 'fee_policy::EClassDoesNotExist'
  | 'fee_policy::EInvalidCancelRetention'
  | 'fee_policy::ENoDefaultClassForQuote'
  | 'fee_policy::EClassQuoteMismatch'
  | 'fee_policy::EDuplicateGenesisClass'
  | 'fee_policy::EInvalidQuoteUnit'
  | 'constants::EOrderInfoMismatch'
  | 'constants::EBookOrderMismatch'
  | 'constants::EIncorrectMidPrice'
  | 'constants::EIncorrectPoolId'
  | 'constants::EFillMismatch'
  | 'constants::EBookOrderNotFound'
  | 'math::EInvalidPrecision'
  | 'math::EOverflow'
  | 'multicoin_pool::EInvalidFee'
  | 'multicoin_pool::EInvalidQuantityIn'
  | 'multicoin_pool::EInvalidOrderTradingAccount'
  | 'multicoin_pool::EPackageVersionDisabled'
  | 'multicoin_pool::EMinimumQuantityOutNotMet'
  | 'multicoin_pool::EPoolNotRegistered'
  | 'multicoin_pool::EQuoteNotApproved'
  | 'pool::EInvalidFee'
  | 'pool::ESameBaseAndQuote'
  | 'pool::EInvalidQuantityIn'
  | 'pool::EInvalidOrderTradingAccount'
  | 'pool::EPackageVersionDisabled'
  | 'pool::EMinimumQuantityOutNotMet'
  | 'pool::EPoolNotRegistered'
  | 'pool::EQuoteNotApproved'
  | 'registry::EPoolAlreadyExists'
  | 'registry::EPoolDoesNotExist'
  | 'registry::EPackageVersionNotEnabled'
  | 'registry::EVersionNotEnabled'
  | 'registry::EVersionAlreadyEnabled'
  | 'registry::ECannotDisableCurrentVersion'
  | 'registry::EMaxTradingAccountsReached'
  | 'registry::EQuoteNotApproved'
  | 'registry::EQuoteAlreadyApproved'
  | 'registry::EMulticoinPoolAlreadyExists'
  | 'registry::EMulticoinPoolDoesNotExist'
  | 'registry::EQuoteInsufficientDecimals'
  | 'fee_schedule::EEmptySchedule'
  | 'fee_schedule::EFirstTierNotZero'
  | 'fee_schedule::EThresholdsNotAscending'
  | 'fee_schedule::ETakerRateNotMonotone'
  | 'fee_schedule::EMakerRateNotMonotone'
  | 'fee_schedule::ETooManyTiers'
  | 'fee_schedule::EInvalidTakerFee'
  | 'fee_schedule::EInvalidMakerFee'
  | 'fee_schedule::EVectorLengthMismatch'
  | 'fee_turnover::EEpochAhead'
  | 'history::EHistoricVolumesNotFound'
  | 'state::EMaxOpenOrders'
  | 'trading_account::EInvalidOwner'
  | 'trading_account::EInvalidTrader'
  | 'trading_account::EInvalidProof'
  | 'trading_account::ETradingAccountBalanceTooLow'
  | 'trading_account::EMaxCapsReached'
  | 'trading_account::ECapNotInList'
  | 'trading_account::EMultiCoinBalanceTooLow'
  | 'multicoin_vault::EInsufficientBaseBalance'
  | 'multicoin_vault::EInsufficientQuoteBalance'
  | 'multicoin_vault::EInsufficientCredBalance'
  | 'multicoin_vault::EInsufficientFeeReserve'
  | 'multicoin_vault::EFeesLocked'
  | 'multicoin_vault::ENoBalanceToSettle'
  | 'multicoin_vault::EHasOwedBalances'
  | 'vault::EInsufficientFeeReserve'
  | 'vault::EFeesLocked'
  | 'vault::ENoBalanceToSettle'
  | 'vault::EHasOwedBalances'

export interface MoveAbortEntry {
  /** The Move constant's name, e.g. `EInvalidFee`. */
  name: string
  /** Label derived from the constant's doc comment, or from its name. */
  label: string
  /** The `#[error]` message string, when the constant declares one. */
  message: string | null
  /** Whether the constant is a clever error (`#[error(code = N)]`). */
  clever: boolean
  /** Where the constant is declared, for debugging. */
  source: string
}

/** Abort entries keyed by module name, then by abort code. */
export const MOVE_ABORT_CATALOG: Record<
  string,
  Record<number, MoveAbortEntry>
> = {
  "book": {
    "1": {
      "name": "EInvalidAmountIn",
      "label": "Invalid amount in",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:10"
    },
    "2": {
      "name": "EEmptyOrderbook",
      "label": "Empty orderbook",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:11"
    },
    "3": {
      "name": "EInvalidPriceRange",
      "label": "Invalid price range",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:12"
    },
    "4": {
      "name": "EInvalidTicks",
      "label": "Invalid ticks",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:13"
    },
    "7": {
      "name": "ENewQuantityMustBeLessThanOriginal",
      "label": "New quantity must be less than original",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:14"
    },
    "8": {
      "name": "EBookOrderNotFound",
      "label": "Book order not found",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:15"
    }
  },
  "order": {
    "0": {
      "name": "EInvalidNewQuantity",
      "label": "Invalid new quantity",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:8"
    },
    "1": {
      "name": "EOrderExpired",
      "label": "Order expired",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:9"
    }
  },
  "order_info": {
    "0": {
      "name": "EOrderInvalidPrice",
      "label": "Order invalid price",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:15"
    },
    "3": {
      "name": "EInvalidExpireTimestamp",
      "label": "Invalid expire timestamp",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:16"
    },
    "4": {
      "name": "EInvalidOrderType",
      "label": "Invalid order type",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:17"
    },
    "5": {
      "name": "EPOSTOrderCrossesOrderbook",
      "label": "POSTOrder crosses orderbook",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:18"
    },
    "6": {
      "name": "EFOKOrderCannotBeFullyFilled",
      "label": "FOKOrder cannot be fully filled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:19"
    },
    "7": {
      "name": "EMarketOrderCannotBePostOnly",
      "label": "Market order cannot be post only",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:20"
    },
    "8": {
      "name": "ESelfMatchingCancelTaker",
      "label": "Self matching cancel taker",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:21"
    }
  },
  "fee_policy": {
    "0": {
      "name": "EClassAlreadyExists",
      "label": "Class already exists",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:23"
    },
    "1": {
      "name": "EClassDoesNotExist",
      "label": "Class does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:24"
    },
    "2": {
      "name": "EInvalidCancelRetention",
      "label": "Invalid cancel retention",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:25"
    },
    "3": {
      "name": "ENoDefaultClassForQuote",
      "label": "No default class for quote",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:26"
    },
    "4": {
      "name": "EClassQuoteMismatch",
      "label": "Class quote mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:27"
    },
    "5": {
      "name": "EDuplicateGenesisClass",
      "label": "Duplicate genesis class",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:28"
    },
    "6": {
      "name": "EInvalidQuoteUnit",
      "label": "Invalid quote unit",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:29"
    }
  },
  "constants": {
    "0": {
      "name": "EOrderInfoMismatch",
      "label": "Order info mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:95"
    },
    "1": {
      "name": "EBookOrderMismatch",
      "label": "Book order mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:97"
    },
    "2": {
      "name": "EIncorrectMidPrice",
      "label": "Incorrect mid price",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:99"
    },
    "3": {
      "name": "EIncorrectPoolId",
      "label": "Incorrect pool id",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:101"
    },
    "4": {
      "name": "EFillMismatch",
      "label": "Fill mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:103"
    },
    "8": {
      "name": "EBookOrderNotFound",
      "label": "Book order not found",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:106"
    }
  },
  "math": {
    "0": {
      "name": "EInvalidPrecision",
      "label": "Error codes",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/math.move:9"
    },
    "1": {
      "name": "EOverflow",
      "label": "Overflow",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/math.move:10"
    }
  },
  "multicoin_pool": {
    "1": {
      "name": "EInvalidFee",
      "label": "Invalid fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:33"
    },
    "8": {
      "name": "EInvalidQuantityIn",
      "label": "Invalid quantity in",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:34"
    },
    "9": {
      "name": "EInvalidOrderTradingAccount",
      "label": "Invalid order trading account",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:35"
    },
    "11": {
      "name": "EPackageVersionDisabled",
      "label": "Package version disabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:36"
    },
    "13": {
      "name": "EMinimumQuantityOutNotMet",
      "label": "Minimum quantity out not met",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:37"
    },
    "14": {
      "name": "EPoolNotRegistered",
      "label": "Pool not registered",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:38"
    },
    "20": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:39"
    }
  },
  "pool": {
    "1": {
      "name": "EInvalidFee",
      "label": "Invalid fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:32"
    },
    "2": {
      "name": "ESameBaseAndQuote",
      "label": "Same base and quote",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:33"
    },
    "6": {
      "name": "EInvalidQuantityIn",
      "label": "Invalid quantity in",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:34"
    },
    "9": {
      "name": "EInvalidOrderTradingAccount",
      "label": "Invalid order trading account",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:35"
    },
    "11": {
      "name": "EPackageVersionDisabled",
      "label": "Package version disabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:36"
    },
    "12": {
      "name": "EMinimumQuantityOutNotMet",
      "label": "Minimum quantity out not met",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:37"
    },
    "14": {
      "name": "EPoolNotRegistered",
      "label": "Pool not registered",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:39"
    },
    "20": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:44"
    }
  },
  "registry": {
    "1": {
      "name": "EPoolAlreadyExists",
      "label": "Pool already exists",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:15"
    },
    "2": {
      "name": "EPoolDoesNotExist",
      "label": "Pool does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:16"
    },
    "3": {
      "name": "EPackageVersionNotEnabled",
      "label": "Package version not enabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:17"
    },
    "4": {
      "name": "EVersionNotEnabled",
      "label": "Version not enabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:18"
    },
    "5": {
      "name": "EVersionAlreadyEnabled",
      "label": "Version already enabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:19"
    },
    "6": {
      "name": "ECannotDisableCurrentVersion",
      "label": "Cannot disable current version",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:20"
    },
    "9": {
      "name": "EMaxTradingAccountsReached",
      "label": "Max trading accounts reached",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:21"
    },
    "10": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:22"
    },
    "11": {
      "name": "EQuoteAlreadyApproved",
      "label": "Quote already approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:23"
    },
    "13": {
      "name": "EMulticoinPoolAlreadyExists",
      "label": "Multicoin pool already exists",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:24"
    },
    "14": {
      "name": "EMulticoinPoolDoesNotExist",
      "label": "Multicoin pool does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:25"
    },
    "15": {
      "name": "EQuoteInsufficientDecimals",
      "label": "Quote insufficient decimals",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:26"
    }
  },
  "fee_schedule": {
    "0": {
      "name": "EEmptySchedule",
      "label": "Empty schedule",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:16"
    },
    "1": {
      "name": "EFirstTierNotZero",
      "label": "First tier not zero",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:17"
    },
    "2": {
      "name": "EThresholdsNotAscending",
      "label": "Thresholds not ascending",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:18"
    },
    "3": {
      "name": "ETakerRateNotMonotone",
      "label": "Taker rate not monotone",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:19"
    },
    "4": {
      "name": "EMakerRateNotMonotone",
      "label": "Maker rate not monotone",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:20"
    },
    "5": {
      "name": "ETooManyTiers",
      "label": "Too many tiers",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:21"
    },
    "6": {
      "name": "EInvalidTakerFee",
      "label": "Invalid taker fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:22"
    },
    "7": {
      "name": "EInvalidMakerFee",
      "label": "Invalid maker fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:23"
    },
    "8": {
      "name": "EVectorLengthMismatch",
      "label": "Vector length mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:24"
    }
  },
  "fee_turnover": {
    "0": {
      "name": "EEpochAhead",
      "label": "Epoch ahead",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_turnover.move:20"
    }
  },
  "history": {
    "0": {
      "name": "EHistoricVolumesNotFound",
      "label": "Historic volumes not found",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/history.move:15"
    }
  },
  "state": {
    "2": {
      "name": "EMaxOpenOrders",
      "label": "Max open orders",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/state.move:20"
    }
  },
  "trading_account": {
    "0": {
      "name": "EInvalidOwner",
      "label": "Invalid owner",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:26"
    },
    "1": {
      "name": "EInvalidTrader",
      "label": "Invalid trader",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:27"
    },
    "2": {
      "name": "EInvalidProof",
      "label": "Invalid proof",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:28"
    },
    "3": {
      "name": "ETradingAccountBalanceTooLow",
      "label": "Trading account balance too low",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:29"
    },
    "4": {
      "name": "EMaxCapsReached",
      "label": "Max caps reached",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:30"
    },
    "5": {
      "name": "ECapNotInList",
      "label": "Cap not in list",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:31"
    },
    "7": {
      "name": "EMultiCoinBalanceTooLow",
      "label": "Multi coin balance too low",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:34"
    }
  },
  "multicoin_vault": {
    "1": {
      "name": "EInsufficientBaseBalance",
      "label": "Insufficient base balance",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:12"
    },
    "2": {
      "name": "EInsufficientQuoteBalance",
      "label": "Insufficient quote balance",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:13"
    },
    "3": {
      "name": "EInsufficientCredBalance",
      "label": "Insufficient cred balance",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:14"
    },
    "5": {
      "name": "EInsufficientFeeReserve",
      "label": "Insufficient fee reserve",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:15"
    },
    "6": {
      "name": "EFeesLocked",
      "label": "Fees locked",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:16"
    },
    "7": {
      "name": "ENoBalanceToSettle",
      "label": "No balance to settle",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:17"
    },
    "8": {
      "name": "EHasOwedBalances",
      "label": "Has owed balances",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:18"
    }
  },
  "vault": {
    "0": {
      "name": "EInsufficientFeeReserve",
      "label": "Insufficient fee reserve",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/vault.move:10"
    },
    "1": {
      "name": "EFeesLocked",
      "label": "Fees locked",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/vault.move:11"
    },
    "7": {
      "name": "ENoBalanceToSettle",
      "label": "No balance to settle",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/vault.move:12"
    },
    "8": {
      "name": "EHasOwedBalances",
      "label": "Has owed balances",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/vault.move:13"
    }
  }
}
