// Generated by scripts/generate-error-codes.mjs — do not edit by hand.
// Sources: trinary-exchange/packages/triex/sources, trinary-exchange/packages/token/sources, armature/packages/armature_framework/sources, armature/packages/armature_proposals/sources, armature-vault/packages/armature_vault/sources, armature-trading/packages/armature_trading/sources
// Regenerate: npm run generate:error-codes

/** Every abort constant declared by the contracts, as `module::EConstantName`. */
export type MoveAbortName =
  | 'book::EInvalidAmountIn'
  | 'book::EEmptyOrderbook'
  | 'book::EInvalidPriceRange'
  | 'book::EInvalidTicks'
  | 'book::ENewQuantityMustBeLessThanOriginal'
  | 'order::EInvalidNewQuantity'
  | 'order::EOrderExpired'
  | 'order::EMakerFeeRateTooWide'
  | 'order::ECancelRetentionTooWide'
  | 'order::EOrderBelowMinimumSize'
  | 'order_info::EOrderInvalidPrice'
  | 'order_info::EOrderBelowMinimumSize'
  | 'order_info::EInvalidExpireTimestamp'
  | 'order_info::EInvalidOrderType'
  | 'order_info::EPOSTOrderCrossesOrderbook'
  | 'order_info::EFOKOrderCannotBeFullyFilled'
  | 'order_info::EMarketOrderCannotBePostOnly'
  | 'order_info::ESelfMatchingCancelTaker'
  | 'fee_policy::EClassAlreadyExists'
  | 'fee_policy::EClassDoesNotExist'
  | 'fee_policy::EInvalidCancelRetention'
  | 'fee_policy::ENoDefaultClassForQuote'
  | 'fee_policy::EClassQuoteMismatch'
  | 'fee_policy::EDuplicateGenesisClass'
  | 'fee_policy::EInvalidQuoteUnit'
  | 'fee_policy::EOperatorShareAboveCeiling'
  | 'fee_policy::EOperatorShareClassDoesNotExist'
  | 'fee_policy::ENoAuthorizedAdapter'
  | 'fee_policy::EUnauthorizedAdapter'
  | 'fee_policy::EAdapterPinned'
  | 'big_vector::ESliceTooSmall'
  | 'big_vector::ESliceTooBig'
  | 'big_vector::EFanOutTooSmall'
  | 'big_vector::EFanOutTooBig'
  | 'big_vector::ENotEmpty'
  | 'big_vector::ENotFound'
  | 'big_vector::EExists'
  | 'big_vector::EBadRemove'
  | 'big_vector::ENotAdjacent'
  | 'big_vector::EBadRedistribution'
  | 'constants::EOrderInfoMismatch'
  | 'constants::EBookOrderMismatch'
  | 'constants::EIncorrectPoolId'
  | 'constants::EFillMismatch'
  | 'math::EInvalidPrecision'
  | 'math::EOverflow'
  | 'multicoin_pool::EInvalidFee'
  | 'multicoin_pool::EInvalidQuantityIn'
  | 'multicoin_pool::EInvalidOrderTradingAccount'
  | 'multicoin_pool::EPackageVersionDisabled'
  | 'multicoin_pool::EMinimumQuantityOutNotMet'
  | 'multicoin_pool::EPoolNotRegistered'
  | 'multicoin_pool::EQuoteNotApproved'
  | 'multicoin_pool::ENoOperatorBeneficiary'
  | 'pool::EInvalidFee'
  | 'pool::ESameBaseAndQuote'
  | 'pool::EInvalidQuantityIn'
  | 'pool::EInvalidOrderTradingAccount'
  | 'pool::EPackageVersionDisabled'
  | 'pool::EMinimumQuantityOutNotMet'
  | 'pool::EPoolNotRegistered'
  | 'pool::EQuoteNotApproved'
  | 'pool::EInvalidDecimalPair'
  | 'registry::EPoolAlreadyExists'
  | 'registry::EPoolDoesNotExist'
  | 'registry::EPackageVersionNotEnabled'
  | 'registry::EVersionNotEnabled'
  | 'registry::EVersionAlreadyEnabled'
  | 'registry::EMaxTradingAccountsReached'
  | 'registry::EQuoteNotApproved'
  | 'registry::EQuoteAlreadyApproved'
  | 'registry::EMulticoinPoolAlreadyExists'
  | 'registry::EMulticoinPoolDoesNotExist'
  | 'registry::EQuoteInsufficientDecimals'
  | 'fee_schedule::EEmptySchedule'
  | 'fee_schedule::EFirstTierNotZero'
  | 'fee_schedule::EThresholdsNotAscending'
  | 'fee_schedule::ETakerRateNotMonotone'
  | 'fee_schedule::EMakerRateNotMonotone'
  | 'fee_schedule::ETooManyTiers'
  | 'fee_schedule::EInvalidTakerFee'
  | 'fee_schedule::EInvalidMakerFee'
  | 'fee_schedule::EVectorLengthMismatch'
  | 'fee_turnover::EEpochAhead'
  | 'state::EMaxOpenOrders'
  | 'trading_account::EInvalidOwner'
  | 'trading_account::EInvalidTrader'
  | 'trading_account::EInvalidProof'
  | 'trading_account::ETradingAccountBalanceTooLow'
  | 'trading_account::EMaxCapsReached'
  | 'trading_account::ECapNotInList'
  | 'trading_account::EMultiCoinBalanceTooLow'
  | 'coin_vault::EInsufficientFeeReserve'
  | 'coin_vault::EFeesLocked'
  | 'coin_vault::ENoBalanceToSettle'
  | 'coin_vault::EHasOwedBalances'
  | 'multicoin_vault::EInsufficientBaseBalance'
  | 'multicoin_vault::EInsufficientQuoteBalance'
  | 'multicoin_vault::EInsufficientCredBalance'
  | 'multicoin_vault::EInsufficientFeeReserve'
  | 'multicoin_vault::EFeesLocked'
  | 'multicoin_vault::ENoBalanceToSettle'
  | 'multicoin_vault::EHasOwedBalances'
  | 'multicoin_vault::EOperatorShareAboveCeiling'
  | 'board_voting::EOUNotActive'
  | 'board_voting::ETypeNotEnabled'
  | 'board_voting::EOUIdMismatch'
  | 'board_voting::EControllerPaused'
  | 'board_voting::EProposeThresholdNotMet'
  | 'board_voting::EFloorNotMet'
  | 'board_voting::EDelayForbidsAtomicExecution'
  | 'board_voting::EInsufficientVotingWeight'
  | 'board_voting::ECooldownRequiresMutableOU'
  | 'capability_vault::ENotController'
  | 'capability_vault::ECapIdMismatch'
  | 'capability_vault::EVaultIdMismatch'
  | 'capability_vault::EOUIdMismatch'
  | 'charter::EOuMismatch'
  | 'composite::ENotComposable'
  | 'composite::EStepTypeMismatch'
  | 'composite::EFrameMismatch'
  | 'composite::EPipelineComplete'
  | 'composite::EPipelineIncomplete'
  | 'composite::ECompositeNesting'
  | 'composite::EOUIdMismatch'
  | 'composite::EOUNotActive'
  | 'composite::EFloorNotMet'
  | 'composite::EEmptyFrame'
  | 'composite::ECooldownTypeNotComposable'
  | 'composite::EFrameNotSealed'
  | 'composite::EFrameAlreadySealed'
  | 'composite::EFrameContentsMismatch'
  | 'composite::EFrameNotExhausted'
  | 'composite::EUseTypedStep'
  | 'composite::EGrantInComposite'
  | 'composite::ETargetNotEnabled'
  | 'composite::EExecutionPaused'
  | 'composite::EControllerPaused'
  | 'composite::ETypeNotEnabled'
  | 'controller::EControlMismatch'
  | 'controller::EOUNotActive'
  | 'controller::ENotController'
  | 'emergency::EOUMismatch'
  | 'emergency::EProtectedType'
  | 'emergency::EFrozen'
  | 'emergency::ENotFrozen'
  | 'emergency::EMandatoryExemptType'
  | 'encrypted_entry::ENotMember'
  | 'encrypted_entry::EEntriesCapReached'
  | 'encrypted_entry::EOuMismatch'
  | 'encrypted_entry::EEntryNotStale'
  | 'encrypted_entry::EOUNotActive'
  | 'encrypted_entry::EIdTooShort'
  | 'external_execution::EOUNotActive'
  | 'external_execution::ETypeNotEnabled'
  | 'external_execution::EExecutionPaused'
  | 'external_execution::EControllerPaused'
  | 'external_execution::ETypeMismatch'
  | 'external_execution::ECooldownActive'
  | 'external_execution::EOUIdMismatch'
  | 'external_execution::EVaultOUMismatch'
  | 'external_execution::EApprovalFloorNotMet'
  | 'external_execution::ESubOUBlockedType'
  | 'external_execution::ECapNotFound'
  | 'external_execution::ESelfBootstrapDenied'
  | 'external_execution::EComposableCooldownConflict'
  | 'external_execution::ECooldownRequiresMutableOU'
  | 'external_execution::EBypassForbiddenBits'
  | 'governance::EEmptyBoard'
  | 'governance::EDuplicateBoardMember'
  | 'governance::ENotBoardMember'
  | 'governance::ENoBoardChange'
  | 'admin_ops::EOuMismatch'
  | 'admin_ops::ECharterOuMismatch'
  | 'admin_ops::EUndisableableType'
  | 'admin_ops::ESubOUBlockedType'
  | 'admin_ops::EFloorNotMet'
  | 'admin_ops::EComposableCooldownConflict'
  | 'admin_ops::ETypeMismatch'
  | 'admin_ops::ETypeNotEnabled'
  | 'board_ops::EOuMismatch'
  | 'freeze_ops::EFreezeOuMismatch'
  | 'freeze_ops::ECapOuMismatch'
  | 'lifecycle_ops::EVaultOUMismatch'
  | 'lifecycle_ops::ESubOUVaultMismatch'
  | 'lifecycle_ops::EOUMismatch'
  | 'lifecycle_ops::EAssetLimitExceeded'
  | 'lifecycle_ops::ETargetTreasuryMismatch'
  | 'lifecycle_ops::ETargetVaultMismatch'
  | 'lifecycle_ops::ETargetOUMismatch'
  | 'lifecycle_ops::ESourceMismatch'
  | 'lifecycle_ops::EAssetNotListed'
  | 'lifecycle_ops::EAssetsRemaining'
  | 'member_ops::EOuMismatch'
  | 'member_ops::EEmptyBatch'
  | 'member_ops::EBatchTooLarge'
  | 'ou::EInvalidName'
  | 'ou::EOUIdMismatch'
  | 'ou::ENotMigrating'
  | 'ou::ETreasuryIdMismatch'
  | 'ou::EVaultIdMismatch'
  | 'ou::ECharterIdMismatch'
  | 'ou::EFreezeIdMismatch'
  | 'ou::EEntriesNotEmpty'
  | 'ou::EEntryIdNotFound'
  | 'ou::EBlockedProposalType'
  | 'ou::EThresholdBelowMinimum'
  | 'ou::ETypeNotEnabled'
  | 'ou::ETypeAlreadyEnabled'
  | 'ou::EDisplayKeyTaken'
  | 'ou::EEmptyDisplayKey'
  | 'ou::EDisplayKeyMismatch'
  | 'ou::EPermissionChangeNotAllowed'
  | 'ou::EGrantFloorNotMet'
  | 'ou::EFixedPermissions'
  | 'ou::ENotPrivileged'
  | 'ou::EBypassQuorumTooLow'
  | 'ou::EEnableQuorumTooLow'
  | 'ou::EUpdateConfigQuorumTooLow'
  | 'ou::EUndisableableType'
  | 'permissions::EUnknownPermission'
  | 'proposal::EInvalidQuorum'
  | 'proposal::EInvalidApprovalThreshold'
  | 'proposal::EInvalidExpiryMs'
  | 'proposal::ENotActive'
  | 'proposal::ENotPassed'
  | 'proposal::EAlreadyVoted'
  | 'proposal::ENotInSnapshot'
  | 'proposal::ENotEligible'
  | 'proposal::EDelayNotElapsed'
  | 'proposal::ECooldownActive'
  | 'proposal::ENotExpired'
  | 'proposal::ETypeNotEnabled'
  | 'proposal::EExecutionPaused'
  | 'proposal::EOUNotActive'
  | 'proposal::ECapOUMismatch'
  | 'proposal::ENotStandaloneTicket'
  | 'proposal::EExecutionWindowClosed'
  | 'proposal::EVotingClosed'
  | 'proposal::EPermissionDenied'
  | 'proposal::EBorrowScopeDenied'
  | 'spend_guard::EExceedsEpochLimit'
  | 'treasury_vault::EInsufficientBalance'
  | 'treasury_vault::EOUIdMismatch'
  | 'treasury_vault::EVaultNotEmpty'
  | 'configure_mint_allowance::EOuMismatch'
  | 'configure_mint_allowance::ETooManyOps'
  | 'configure_mint_allowance::ETooManyMinters'
  | 'currency_ops::EVaultOUMismatch'
  | 'currency_ops::ECapNotInVault'
  | 'currency_ops::ECapTypeMismatch'
  | 'currency_ops::EAllowanceNotConfigured'
  | 'currency_ops::EAllowanceDisabled'
  | 'currency_ops::ENotAllowedMinter'
  | 'currency_ops::EExceedsAllowance'
  | 'subou_ops::EVaultOUMismatch'
  | 'subou_ops::ESubOUVaultMismatch'
  | 'subou_ops::EEmptyBatch'
  | 'subou_ops::EBatchTooLarge'
  | 'treasury_ops::EVaultOUMismatch'
  | 'treasury_ops::ETargetVaultMismatch'
  | 'treasury_ops::EExceedsDailyCap'
  | 'upgrade_ops::EVaultOuMismatch'
  | 'keyspace::ENotAllowed'
  | 'keyspace::EAlreadyGranted'
  | 'keyspace::ENotGranted'
  | 'keyspace::EAlreadyCurrentEpoch'
  | 'keyspace::EWrongKeyspace'
  | 'keyspace::ELastGrantor'
  | 'keyspace::ELastWriter'
  | 'keyspace::ELastReader'
  | 'keyspace::EEmptyGrantPrincipals'
  | 'ou_receipt_vault::ENotAuthorized'
  | 'ou_receipt_vault::EInsufficientVaultBalance'
  | 'ou_receipt_vault::EWrongCollection'
  | 'ou_receipt_vault::EVaultAlreadyExists'
  | 'ou_receipt_vault::ELastEditor'
  | 'ou_receipt_vault::EInvalidArguments'
  | 'ou_receipt_vault::EZeroAmount'
  | 'ou_receipt_vault::EEditorWouldLockSelf'
  | 'ou_receipt_vault::EVaultNonEmpty'
  | 'ou_receipt_vault::EVaultRegistryMismatch'
  | 'ou_receipt_vault::EStorageUnitMismatch'
  | 'ou_receipt_vault::EEmptyEditPrincipals'
  | 'trading_ops::EWrongTradingAccount'
  | 'trading_ops::EWrongCustody'
  | 'trading_ops::EWrongVault'
  | 'trading_ops::EWrongPool'
  | 'trading_ops::EWrongOu'
  | 'trading_ops::EWrongTreasury'
  | 'trading_ops::EWrongCollection'

export interface MoveAbortEntry {
  /** The Move constant's name, e.g. `EInvalidFee`. */
  name: string
  /** Label derived from the constant's doc comment, or from its name. */
  label: string
  /** The `#[error]` message string, when the constant declares one. */
  message: string | null
  /** Whether the constant is a clever error (`#[error(code = N)]`). */
  clever: boolean
  /** Where the constant is declared, for debugging. */
  source: string
}

/** Abort entries keyed by module name, then by abort code. */
export const MOVE_ABORT_CATALOG: Record<
  string,
  Record<number, MoveAbortEntry>
> = {
  "book": {
    "1": {
      "name": "EInvalidAmountIn",
      "label": "Invalid amount in",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/book.move:45"
    },
    "2": {
      "name": "EEmptyOrderbook",
      "label": "Empty orderbook",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/book.move:46"
    },
    "3": {
      "name": "EInvalidPriceRange",
      "label": "Invalid price range",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/book.move:47"
    },
    "4": {
      "name": "EInvalidTicks",
      "label": "Invalid ticks",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/book.move:48"
    },
    "7": {
      "name": "ENewQuantityMustBeLessThanOriginal",
      "label": "New quantity must be less than original",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/book.move:49"
    }
  },
  "order": {
    "0": {
      "name": "EInvalidNewQuantity",
      "label": "Invalid new quantity",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order.move:8"
    },
    "1": {
      "name": "EOrderExpired",
      "label": "Order expired",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order.move:9"
    },
    "2": {
      "name": "EMakerFeeRateTooWide",
      "label": "A snapshotted rate was out of range, or finer than the whole basis point the order stores. The real bounds are enforced where the rates are set, in `triex::fee_policy`; these are the backstop that keeps the encoding total.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order.move:13"
    },
    "3": {
      "name": "ECancelRetentionTooWide",
      "label": "Cancel retention too wide",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order.move:14"
    },
    "4": {
      "name": "EOrderBelowMinimumSize",
      "label": "Order below minimum size",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order.move:15"
    }
  },
  "order_info": {
    "0": {
      "name": "EOrderInvalidPrice",
      "label": "Order invalid price",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:18"
    },
    "1": {
      "name": "EOrderBelowMinimumSize",
      "label": "Bound derived from the order's own price rather than a per-pool constant.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:20"
    },
    "3": {
      "name": "EInvalidExpireTimestamp",
      "label": "Invalid expire timestamp",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:21"
    },
    "4": {
      "name": "EInvalidOrderType",
      "label": "Invalid order type",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:22"
    },
    "5": {
      "name": "EPOSTOrderCrossesOrderbook",
      "label": "POSTOrder crosses orderbook",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:23"
    },
    "6": {
      "name": "EFOKOrderCannotBeFullyFilled",
      "label": "FOKOrder cannot be fully filled",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:24"
    },
    "7": {
      "name": "EMarketOrderCannotBePostOnly",
      "label": "Market order cannot be post only",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:25"
    },
    "8": {
      "name": "ESelfMatchingCancelTaker",
      "label": "Self matching cancel taker",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/book/order_info.move:26"
    }
  },
  "fee_policy": {
    "0": {
      "name": "EClassAlreadyExists",
      "label": "Class already exists",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:26"
    },
    "1": {
      "name": "EClassDoesNotExist",
      "label": "Class does not exist",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:27"
    },
    "2": {
      "name": "EInvalidCancelRetention",
      "label": "Invalid cancel retention",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:28"
    },
    "3": {
      "name": "ENoDefaultClassForQuote",
      "label": "No default class for quote",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:29"
    },
    "4": {
      "name": "EClassQuoteMismatch",
      "label": "Class quote mismatch",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:30"
    },
    "5": {
      "name": "EDuplicateGenesisClass",
      "label": "Duplicate genesis class",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:31"
    },
    "6": {
      "name": "EInvalidQuoteUnit",
      "label": "Invalid quote unit",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:32"
    },
    "7": {
      "name": "EOperatorShareAboveCeiling",
      "label": "Operator share above ceiling",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:33"
    },
    "8": {
      "name": "EOperatorShareClassDoesNotExist",
      "label": "Operator share class does not exist",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:34"
    },
    "9": {
      "name": "ENoAuthorizedAdapter",
      "label": "No authorized adapter",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:35"
    },
    "10": {
      "name": "EUnauthorizedAdapter",
      "label": "Unauthorized adapter",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:36"
    },
    "11": {
      "name": "EAdapterPinned",
      "label": "Adapter pinned",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/fee_policy.move:37"
    }
  },
  "big_vector": {
    "0": {
      "name": "ESliceTooSmall",
      "label": "Max Slice Size provided is too small.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:79"
    },
    "1": {
      "name": "ESliceTooBig",
      "label": "Max Slice Size provided is too big.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:82"
    },
    "2": {
      "name": "EFanOutTooSmall",
      "label": "Max Fan-out provided is too small.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:85"
    },
    "3": {
      "name": "EFanOutTooBig",
      "label": "Max Fan-out provided is too big.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:88"
    },
    "4": {
      "name": "ENotEmpty",
      "label": "`BigVector` is not empty.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:91"
    },
    "5": {
      "name": "ENotFound",
      "label": "Key not found in `BigVector`.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:94"
    },
    "6": {
      "name": "EExists",
      "label": "Key already exists in `BigVector`.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:97"
    },
    "7": {
      "name": "EBadRemove",
      "label": "Found a node in an unexpected state during removal (namely, we tried to remove from a node's child and found that it had become empty, which should not be possible).",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:102"
    },
    "8": {
      "name": "ENotAdjacent",
      "label": "Found a pair of nodes that are expected to be adjacent but whose linked list pointers don't match up.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:106"
    },
    "9": {
      "name": "EBadRedistribution",
      "label": "Tried to redistribute between two nodes, but the operation would have had no effect.",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/big_vector.move:110"
    }
  },
  "constants": {
    "0": {
      "name": "EOrderInfoMismatch",
      "label": "Order info mismatch",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/constants.move:100"
    },
    "1": {
      "name": "EBookOrderMismatch",
      "label": "Book order mismatch",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/constants.move:102"
    },
    "3": {
      "name": "EIncorrectPoolId",
      "label": "Incorrect pool id",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/constants.move:104"
    },
    "4": {
      "name": "EFillMismatch",
      "label": "Fill mismatch",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/constants.move:106"
    }
  },
  "math": {
    "0": {
      "name": "EInvalidPrecision",
      "label": "Error codes",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/math.move:8"
    },
    "1": {
      "name": "EOverflow",
      "label": "Overflow",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/helper/math.move:9"
    }
  },
  "multicoin_pool": {
    "1": {
      "name": "EInvalidFee",
      "label": "Invalid fee",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:34"
    },
    "8": {
      "name": "EInvalidQuantityIn",
      "label": "Invalid quantity in",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:35"
    },
    "9": {
      "name": "EInvalidOrderTradingAccount",
      "label": "Invalid order trading account",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:36"
    },
    "11": {
      "name": "EPackageVersionDisabled",
      "label": "Package version disabled",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:37"
    },
    "13": {
      "name": "EMinimumQuantityOutNotMet",
      "label": "Minimum quantity out not met",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:38"
    },
    "14": {
      "name": "EPoolNotRegistered",
      "label": "Pool not registered",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:39"
    },
    "20": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:40"
    },
    "21": {
      "name": "ENoOperatorBeneficiary",
      "label": "No operator beneficiary",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/multicoin_pool.move:41"
    }
  },
  "pool": {
    "1": {
      "name": "EInvalidFee",
      "label": "Invalid fee",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:35"
    },
    "2": {
      "name": "ESameBaseAndQuote",
      "label": "Same base and quote",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:36"
    },
    "6": {
      "name": "EInvalidQuantityIn",
      "label": "Invalid quantity in",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:37"
    },
    "9": {
      "name": "EInvalidOrderTradingAccount",
      "label": "Invalid order trading account",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:38"
    },
    "11": {
      "name": "EPackageVersionDisabled",
      "label": "Package version disabled",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:39"
    },
    "12": {
      "name": "EMinimumQuantityOutNotMet",
      "label": "Minimum quantity out not met",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:40"
    },
    "14": {
      "name": "EPoolNotRegistered",
      "label": "Pool not registered",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:42"
    },
    "20": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:47"
    },
    "21": {
      "name": "EInvalidDecimalPair",
      "label": "Invalid decimal pair",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/pool.move:48"
    }
  },
  "registry": {
    "1": {
      "name": "EPoolAlreadyExists",
      "label": "Pool already exists",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:15"
    },
    "2": {
      "name": "EPoolDoesNotExist",
      "label": "Pool does not exist",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:16"
    },
    "3": {
      "name": "EPackageVersionNotEnabled",
      "label": "Package version not enabled",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:17"
    },
    "4": {
      "name": "EVersionNotEnabled",
      "label": "Version not enabled",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:18"
    },
    "5": {
      "name": "EVersionAlreadyEnabled",
      "label": "Version already enabled",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:19"
    },
    "9": {
      "name": "EMaxTradingAccountsReached",
      "label": "Max trading accounts reached",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:23"
    },
    "10": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:24"
    },
    "11": {
      "name": "EQuoteAlreadyApproved",
      "label": "Quote already approved",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:25"
    },
    "13": {
      "name": "EMulticoinPoolAlreadyExists",
      "label": "Multicoin pool already exists",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:26"
    },
    "14": {
      "name": "EMulticoinPoolDoesNotExist",
      "label": "Multicoin pool does not exist",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:27"
    },
    "15": {
      "name": "EQuoteInsufficientDecimals",
      "label": "Quote insufficient decimals",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/registry.move:28"
    }
  },
  "fee_schedule": {
    "0": {
      "name": "EEmptySchedule",
      "label": "Empty schedule",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:16"
    },
    "1": {
      "name": "EFirstTierNotZero",
      "label": "First tier not zero",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:17"
    },
    "2": {
      "name": "EThresholdsNotAscending",
      "label": "Thresholds not ascending",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:18"
    },
    "3": {
      "name": "ETakerRateNotMonotone",
      "label": "Taker rate not monotone",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:19"
    },
    "4": {
      "name": "EMakerRateNotMonotone",
      "label": "Maker rate not monotone",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:20"
    },
    "5": {
      "name": "ETooManyTiers",
      "label": "Too many tiers",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:21"
    },
    "6": {
      "name": "EInvalidTakerFee",
      "label": "Invalid taker fee",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:22"
    },
    "7": {
      "name": "EInvalidMakerFee",
      "label": "Invalid maker fee",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:23"
    },
    "8": {
      "name": "EVectorLengthMismatch",
      "label": "Vector length mismatch",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_schedule.move:24"
    }
  },
  "fee_turnover": {
    "0": {
      "name": "EEpochAhead",
      "label": "Epoch ahead",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/fee_turnover.move:20"
    }
  },
  "state": {
    "2": {
      "name": "EMaxOpenOrders",
      "label": "Max open orders",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/state/state.move:20"
    }
  },
  "trading_account": {
    "0": {
      "name": "EInvalidOwner",
      "label": "Invalid owner",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:26"
    },
    "1": {
      "name": "EInvalidTrader",
      "label": "Invalid trader",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:27"
    },
    "2": {
      "name": "EInvalidProof",
      "label": "Invalid proof",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:28"
    },
    "3": {
      "name": "ETradingAccountBalanceTooLow",
      "label": "Trading account balance too low",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:29"
    },
    "4": {
      "name": "EMaxCapsReached",
      "label": "Max caps reached",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:30"
    },
    "5": {
      "name": "ECapNotInList",
      "label": "Cap not in list",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:31"
    },
    "7": {
      "name": "EMultiCoinBalanceTooLow",
      "label": "Multi coin balance too low",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/trading_account.move:34"
    }
  },
  "coin_vault": {
    "0": {
      "name": "EInsufficientFeeReserve",
      "label": "Insufficient fee reserve",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/coin_vault.move:19"
    },
    "1": {
      "name": "EFeesLocked",
      "label": "Fees locked",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/coin_vault.move:20"
    },
    "7": {
      "name": "ENoBalanceToSettle",
      "label": "No balance to settle",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/coin_vault.move:21"
    },
    "8": {
      "name": "EHasOwedBalances",
      "label": "Has owed balances",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/coin_vault.move:22"
    }
  },
  "multicoin_vault": {
    "1": {
      "name": "EInsufficientBaseBalance",
      "label": "Insufficient base balance",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:18"
    },
    "2": {
      "name": "EInsufficientQuoteBalance",
      "label": "Insufficient quote balance",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:19"
    },
    "3": {
      "name": "EInsufficientCredBalance",
      "label": "Insufficient cred balance",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:20"
    },
    "5": {
      "name": "EInsufficientFeeReserve",
      "label": "Insufficient fee reserve",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:21"
    },
    "6": {
      "name": "EFeesLocked",
      "label": "Fees locked",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:22"
    },
    "7": {
      "name": "ENoBalanceToSettle",
      "label": "No balance to settle",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:23"
    },
    "8": {
      "name": "EHasOwedBalances",
      "label": "Has owed balances",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:24"
    },
    "9": {
      "name": "EOperatorShareAboveCeiling",
      "label": "Operator share above ceiling",
      "message": null,
      "clever": false,
      "source": "trinary-exchange/packages/triex/sources/vault/multicoin_vault.move:25"
    }
  },
  "board_voting": {
    "0": {
      "name": "EOUNotActive",
      "label": "OUNot active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:13"
    },
    "1": {
      "name": "ETypeNotEnabled",
      "label": "Type not enabled",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:14"
    },
    "2": {
      "name": "EOUIdMismatch",
      "label": "OUId mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:15"
    },
    "3": {
      "name": "EControllerPaused",
      "label": "Controller paused",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:16"
    },
    "4": {
      "name": "EProposeThresholdNotMet",
      "label": "Propose threshold not met",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:17"
    },
    "6": {
      "name": "EFloorNotMet",
      "label": "Proposal's approval_threshold is below the hardcoded floor for this type. Enforced at submission time so the proposal never enters the object graph.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:20"
    },
    "7": {
      "name": "EDelayForbidsAtomicExecution",
      "label": "submit_vote_execute called for a type whose execution_delay_ms > 0. Atomic execution is impossible when a delay is configured — use submit_proposal instead.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:23"
    },
    "8": {
      "name": "EInsufficientVotingWeight",
      "label": "submit_vote_execute called but the caller's single vote did not satisfy the proposal type's quorum and approval_threshold requirements.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:26"
    },
    "9": {
      "name": "ECooldownRequiresMutableOU",
      "label": "A `_readonly` entry point was called for a type with cooldown_ms > 0. Cooldown tracking writes the type's slot, so those types must use the `&mut OU` variant.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/board_voting.move:29"
    }
  },
  "capability_vault": {
    "0": {
      "name": "ENotController",
      "label": "Not controller",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/capability_vault.move:12"
    },
    "1": {
      "name": "ECapIdMismatch",
      "label": "Cap id mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/capability_vault.move:13"
    },
    "2": {
      "name": "EVaultIdMismatch",
      "label": "Vault id mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/capability_vault.move:14"
    },
    "3": {
      "name": "EOUIdMismatch",
      "label": "OUId mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/capability_vault.move:15"
    }
  },
  "charter": {
    "0": {
      "name": "EOuMismatch",
      "label": "Ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/charter.move:8"
    }
  },
  "composite": {
    "0": {
      "name": "ENotComposable",
      "label": "Not composable",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:32"
    },
    "1": {
      "name": "EStepTypeMismatch",
      "label": "Step type mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:33"
    },
    "2": {
      "name": "EFrameMismatch",
      "label": "Frame mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:34"
    },
    "3": {
      "name": "EPipelineComplete",
      "label": "Pipeline complete",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:35"
    },
    "4": {
      "name": "EPipelineIncomplete",
      "label": "Pipeline incomplete",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:36"
    },
    "5": {
      "name": "ECompositeNesting",
      "label": "Composite nesting",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:37"
    },
    "6": {
      "name": "EOUIdMismatch",
      "label": "OUId mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:38"
    },
    "7": {
      "name": "EOUNotActive",
      "label": "OUNot active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:39"
    },
    "8": {
      "name": "EFloorNotMet",
      "label": "Floor not met",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:40"
    },
    "9": {
      "name": "EEmptyFrame",
      "label": "Empty frame",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:41"
    },
    "11": {
      "name": "ECooldownTypeNotComposable",
      "label": "A type with cooldown_ms > 0 reached advance_step (defence-in-depth).",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:43"
    },
    "12": {
      "name": "EFrameNotSealed",
      "label": "begin_pipeline called with an unsealed CompositeFrame.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:45"
    },
    "13": {
      "name": "EFrameAlreadySealed",
      "label": "Frame write operation attempted after seal_frame.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:47"
    },
    "14": {
      "name": "EFrameContentsMismatch",
      "label": "Frame step_type_keys or step_types do not match the voted-on payload.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:49"
    },
    "15": {
      "name": "EFrameNotExhausted",
      "label": "delete_exhausted_frame called before all steps have been extracted.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:51"
    },
    "16": {
      "name": "EUseTypedStep",
      "label": "EnableProposalType and UpdateProposalConfig steps must go through add_enable_proposal_type_step / add_update_proposal_config_step, which can read the payload.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:55"
    },
    "17": {
      "name": "EGrantInComposite",
      "label": "A step would grant or change permission bits. Grants are standalone-only: composite step tickets carry no vote weights to check a grant floor against.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:58"
    },
    "18": {
      "name": "ETargetNotEnabled",
      "label": "An UpdateProposalConfig step names a display key no enabled type carries.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:60"
    },
    "19": {
      "name": "EExecutionPaused",
      "label": "advance_step on an OU whose execution is paused.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:62"
    },
    "20": {
      "name": "EControllerPaused",
      "label": "advance_step on a SubOU whose controller has paused it.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:64"
    },
    "21": {
      "name": "ETypeNotEnabled",
      "label": "advance_step for a step type the OU has since disabled.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/composite.move:66"
    }
  },
  "controller": {
    "0": {
      "name": "EControlMismatch",
      "label": "Control mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/controller.move:11"
    },
    "1": {
      "name": "EOUNotActive",
      "label": "OUNot active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/controller.move:12"
    },
    "2": {
      "name": "ENotController",
      "label": "The SubOUControl is bound to this SubOU but is not its registered controller (`OU::controller_cap_id`), or the SubOU has none.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/controller.move:15"
    }
  },
  "emergency": {
    "0": {
      "name": "EOUMismatch",
      "label": "OUMismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/emergency.move:15"
    },
    "1": {
      "name": "EProtectedType",
      "label": "Protected type",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/emergency.move:16"
    },
    "2": {
      "name": "EFrozen",
      "label": "Frozen",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/emergency.move:17"
    },
    "3": {
      "name": "ENotFrozen",
      "label": "Not frozen",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/emergency.move:18"
    },
    "4": {
      "name": "EMandatoryExemptType",
      "label": "Mandatory exempt type",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/emergency.move:19"
    }
  },
  "encrypted_entry": {
    "0": {
      "name": "ENotMember",
      "label": "Not member",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/encrypted_entry.move:9"
    },
    "1": {
      "name": "EEntriesCapReached",
      "label": "Entries cap reached",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/encrypted_entry.move:10"
    },
    "2": {
      "name": "EOuMismatch",
      "label": "Ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/encrypted_entry.move:11"
    },
    "3": {
      "name": "EEntryNotStale",
      "label": "Entry not stale",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/encrypted_entry.move:12"
    },
    "4": {
      "name": "EOUNotActive",
      "label": "OUNot active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/encrypted_entry.move:13"
    },
    "5": {
      "name": "EIdTooShort",
      "label": "Id too short",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/encrypted_entry.move:14"
    }
  },
  "external_execution": {
    "0": {
      "name": "EOUNotActive",
      "label": "OUNot active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:37"
    },
    "1": {
      "name": "ETypeNotEnabled",
      "label": "Type not enabled",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:38"
    },
    "2": {
      "name": "EExecutionPaused",
      "label": "Execution paused",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:39"
    },
    "3": {
      "name": "EControllerPaused",
      "label": "Controller paused",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:40"
    },
    "4": {
      "name": "ETypeMismatch",
      "label": "The handler's `NewType` does not match the type pinned in the payload, or the display key in the payload does not match the slot's display key.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:43"
    },
    "5": {
      "name": "ECooldownActive",
      "label": "Cooldown active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:44"
    },
    "6": {
      "name": "EOUIdMismatch",
      "label": "OUId mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:45"
    },
    "7": {
      "name": "EVaultOUMismatch",
      "label": "Vault oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:46"
    },
    "8": {
      "name": "EApprovalFloorNotMet",
      "label": "Approval floor not met",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:47"
    },
    "9": {
      "name": "ESubOUBlockedType",
      "label": "Sub oublocked type",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:48"
    },
    "10": {
      "name": "ECapNotFound",
      "label": "Cap not found",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:49"
    },
    "11": {
      "name": "ESelfBootstrapDenied",
      "label": "Self bootstrap denied",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:50"
    },
    "13": {
      "name": "EComposableCooldownConflict",
      "label": "Config sets cooldown_ms > 0 and composable_allowed = true simultaneously.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:52"
    },
    "14": {
      "name": "ECooldownRequiresMutableOU",
      "label": "`ticket_from_cap_readonly` called for a type with cooldown_ms > 0. Cooldown tracking writes the type's slot, so those types must use `ticket_from_cap`.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:55"
    },
    "15": {
      "name": "EBypassForbiddenBits",
      "label": "The type's slot holds a bit in `bypass_forbidden_bits`: a no-vote path may not change the authority graph (type registry, lifecycle, cap custody, freeze). Checked when the bypass is enabled and again at every mint, so a later UpdateProposalConfig grant cannot open it either.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/external_execution.move:60"
    }
  },
  "governance": {
    "0": {
      "name": "EEmptyBoard",
      "label": "Empty board",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/governance.move:8"
    },
    "1": {
      "name": "EDuplicateBoardMember",
      "label": "Duplicate board member",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/governance.move:9"
    },
    "2": {
      "name": "ENotBoardMember",
      "label": "Not board member",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/governance.move:10"
    },
    "3": {
      "name": "ENoBoardChange",
      "label": "set_board called with nothing to add and nothing to remove.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/governance.move:12"
    }
  },
  "admin_ops": {
    "0": {
      "name": "EOuMismatch",
      "label": "Ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:18"
    },
    "1": {
      "name": "ECharterOuMismatch",
      "label": "Charter ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:19"
    },
    "2": {
      "name": "EUndisableableType",
      "label": "Undisableable type",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:20"
    },
    "4": {
      "name": "ESubOUBlockedType",
      "label": "Sub oublocked type",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:21"
    },
    "6": {
      "name": "EFloorNotMet",
      "label": "Proposal's approval_threshold is below the hardcoded floor for this type. Enforced at submission time by propose_update_proposal_config.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:26"
    },
    "7": {
      "name": "EComposableCooldownConflict",
      "label": "Config sets cooldown_ms > 0 and composable_allowed = true simultaneously.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:28"
    },
    "8": {
      "name": "ETypeMismatch",
      "label": "The executor's `NewType` does not match the type pinned in the EnableProposalType payload.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:30"
    },
    "9": {
      "name": "ETypeNotEnabled",
      "label": "The payload names a display key that no enabled type carries.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/admin_ops.move:32"
    }
  },
  "board_ops": {
    "0": {
      "name": "EOuMismatch",
      "label": "Ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/board_ops.move:10"
    }
  },
  "freeze_ops": {
    "0": {
      "name": "EFreezeOuMismatch",
      "label": "Freeze ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/freeze_ops.move:22"
    },
    "1": {
      "name": "ECapOuMismatch",
      "label": "Cap ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/freeze_ops.move:23"
    }
  },
  "lifecycle_ops": {
    "0": {
      "name": "EVaultOUMismatch",
      "label": "Vault oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:23"
    },
    "1": {
      "name": "ESubOUVaultMismatch",
      "label": "Sub ouvault mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:24"
    },
    "2": {
      "name": "EOUMismatch",
      "label": "OUMismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:25"
    },
    "4": {
      "name": "EAssetLimitExceeded",
      "label": "Asset limit exceeded",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:26"
    },
    "5": {
      "name": "ETargetTreasuryMismatch",
      "label": "Target treasury mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:27"
    },
    "6": {
      "name": "ETargetVaultMismatch",
      "label": "Target vault mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:28"
    },
    "7": {
      "name": "ETargetOUMismatch",
      "label": "Target oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:29"
    },
    "8": {
      "name": "ESourceMismatch",
      "label": "The source treasury or vault is not the one the transfer was begun with.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:31"
    },
    "9": {
      "name": "EAssetNotListed",
      "label": "The coin type or cap ID is not in the TransferAssets payload, or has already been moved.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:34"
    },
    "10": {
      "name": "EAssetsRemaining",
      "label": "finish_transfer_assets called before every listed asset was moved.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/lifecycle_ops.move:36"
    }
  },
  "member_ops": {
    "0": {
      "name": "EOuMismatch",
      "label": "Ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/member_ops.move:13"
    },
    "1": {
      "name": "EEmptyBatch",
      "label": "Empty batch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/member_ops.move:14"
    },
    "2": {
      "name": "EBatchTooLarge",
      "label": "Batch too large",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/handlers/member_ops.move:15"
    }
  },
  "ou": {
    "0": {
      "name": "EInvalidName",
      "label": "Invalid name",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:37"
    },
    "2": {
      "name": "EOUIdMismatch",
      "label": "OUId mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:38"
    },
    "3": {
      "name": "ENotMigrating",
      "label": "Not migrating",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:39"
    },
    "4": {
      "name": "ETreasuryIdMismatch",
      "label": "Treasury id mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:40"
    },
    "5": {
      "name": "EVaultIdMismatch",
      "label": "Vault id mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:41"
    },
    "6": {
      "name": "ECharterIdMismatch",
      "label": "Charter id mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:42"
    },
    "7": {
      "name": "EFreezeIdMismatch",
      "label": "Freeze id mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:43"
    },
    "8": {
      "name": "EEntriesNotEmpty",
      "label": "Entries not empty",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:44"
    },
    "9": {
      "name": "EEntryIdNotFound",
      "label": "Entry id not found",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:45"
    },
    "11": {
      "name": "EBlockedProposalType",
      "label": "Attempted to add or override a blocked proposal type (hierarchy-altering or bypass-meta).",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:47"
    },
    "12": {
      "name": "EThresholdBelowMinimum",
      "label": "Override sets approval_threshold below the hardcoded minimum for the type.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:49"
    },
    "13": {
      "name": "ETypeNotEnabled",
      "label": "The proposal type has no slot on this OU (not enabled).",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:51"
    },
    "14": {
      "name": "ETypeAlreadyEnabled",
      "label": "The proposal type already has a slot on this OU.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:53"
    },
    "15": {
      "name": "EDisplayKeyTaken",
      "label": "Another enabled type already uses this display key.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:55"
    },
    "16": {
      "name": "EEmptyDisplayKey",
      "label": "Display keys must be non-empty.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:57"
    },
    "17": {
      "name": "EDisplayKeyMismatch",
      "label": "Override for an already-enabled type names a display key other than the slot's.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:59"
    },
    "19": {
      "name": "EPermissionChangeNotAllowed",
      "label": "A config change would alter a type's permission bits, but the request is not EnableProposalType, EnableBypassType or UpdateProposalConfig.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:63"
    },
    "21": {
      "name": "EGrantFloorNotMet",
      "label": "The bits being granted need a higher approval floor than the granting meta-type's vote is held to.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:68"
    },
    "23": {
      "name": "EFixedPermissions",
      "label": "A config for a framework type names bits other than its fixed set (`framework_permissions`).",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:72"
    },
    "24": {
      "name": "ENotPrivileged",
      "label": "A controller-only mutator was called with an unprivileged request.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:74"
    },
    "25": {
      "name": "EBypassQuorumTooLow",
      "label": "An EnableBypassType config whose quorum × approval_threshold is below ENABLE_BYPASS_TYPE_MIN_THRESHOLD × 100%: a vote could pass on it yet fail the execution-time floor on the whole board's weight.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:78"
    },
    "26": {
      "name": "EEnableQuorumTooLow",
      "label": "An EnableProposalType config whose quorum × approval_threshold is below ENABLE_PROPOSAL_TYPE_MIN_THRESHOLD × 100%: a minority of the board could pass it and enable a type with high-impact bits.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:82"
    },
    "27": {
      "name": "EUpdateConfigQuorumTooLow",
      "label": "An UpdateProposalConfig config whose quorum × approval_threshold is below UPDATE_PROPOSAL_CONFIG_MIN_THRESHOLD × 100%: a minority of the board could pass it and make any enabled type single-vote.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:86"
    },
    "28": {
      "name": "EUndisableableType",
      "label": "The type is one of the core undisableable types (`is_undisableable_type`).",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/ou.move:88"
    }
  },
  "permissions": {
    "0": {
      "name": "EUnknownPermission",
      "label": "A permissions mask sets a bit that is not defined below.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/permissions.move:16"
    }
  },
  "proposal": {
    "0": {
      "name": "EInvalidQuorum",
      "label": "Invalid quorum",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:15"
    },
    "1": {
      "name": "EInvalidApprovalThreshold",
      "label": "Invalid approval threshold",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:16"
    },
    "2": {
      "name": "EInvalidExpiryMs",
      "label": "Invalid expiry ms",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:17"
    },
    "3": {
      "name": "ENotActive",
      "label": "Not active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:18"
    },
    "4": {
      "name": "ENotPassed",
      "label": "Not passed",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:19"
    },
    "5": {
      "name": "EAlreadyVoted",
      "label": "Already voted",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:20"
    },
    "6": {
      "name": "ENotInSnapshot",
      "label": "Not in snapshot",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:21"
    },
    "7": {
      "name": "ENotEligible",
      "label": "Not eligible",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:22"
    },
    "8": {
      "name": "EDelayNotElapsed",
      "label": "Delay not elapsed",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:23"
    },
    "9": {
      "name": "ECooldownActive",
      "label": "Cooldown active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:24"
    },
    "10": {
      "name": "ENotExpired",
      "label": "Not expired",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:25"
    },
    "11": {
      "name": "ETypeNotEnabled",
      "label": "Type not enabled",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:27"
    },
    "12": {
      "name": "EExecutionPaused",
      "label": "Execution paused",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:28"
    },
    "15": {
      "name": "EOUNotActive",
      "label": "OUNot active",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:29"
    },
    "16": {
      "name": "ECapOUMismatch",
      "label": "Cap oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:30"
    },
    "17": {
      "name": "ENotStandaloneTicket",
      "label": "ticket_yes_weight or ticket_total_snapshot_weight called on a non-vote-path ticket.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:32"
    },
    "19": {
      "name": "EExecutionWindowClosed",
      "label": "execute called on a Passed proposal after its execution window closed.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:34"
    },
    "20": {
      "name": "EVotingClosed",
      "label": "vote called on an Active proposal after its voting period (expiry_ms) ended.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:36"
    },
    "21": {
      "name": "EPermissionDenied",
      "label": "The request's type does not hold the permission bits a mutator requires (see armature::permissions), and the request is not privileged.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:39"
    },
    "22": {
      "name": "EBorrowScopeDenied",
      "label": "The request's type may borrow from the vault (VAULT_BORROW) but the cap type is not in its `borrow_scope`, and the request is not privileged.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/proposal.move:42"
    }
  },
  "spend_guard": {
    "0": {
      "name": "EExceedsEpochLimit",
      "label": "Exceeds epoch limit",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/spend_guard.move:41"
    }
  },
  "treasury_vault": {
    "0": {
      "name": "EInsufficientBalance",
      "label": "Insufficient balance",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/treasury_vault.move:14"
    },
    "1": {
      "name": "EOUIdMismatch",
      "label": "OUId mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/treasury_vault.move:15"
    },
    "2": {
      "name": "EVaultNotEmpty",
      "label": "Vault not empty",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_framework/sources/treasury_vault.move:16"
    }
  },
  "configure_mint_allowance": {
    "0": {
      "name": "EOuMismatch",
      "label": "Ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/configure_mint_allowance.move:21"
    },
    "1": {
      "name": "ETooManyOps",
      "label": "Too many ops",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/configure_mint_allowance.move:22"
    },
    "2": {
      "name": "ETooManyMinters",
      "label": "Too many minters",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/configure_mint_allowance.move:23"
    }
  },
  "currency_ops": {
    "0": {
      "name": "EVaultOUMismatch",
      "label": "Vault oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:21"
    },
    "1": {
      "name": "ECapNotInVault",
      "label": "Cap not in vault",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:22"
    },
    "2": {
      "name": "ECapTypeMismatch",
      "label": "Cap type mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:23"
    },
    "3": {
      "name": "EAllowanceNotConfigured",
      "label": "No `ConfigureMintAllowance<T>` has run on this OU.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:25"
    },
    "4": {
      "name": "EAllowanceDisabled",
      "label": "The allowance kill-switch is off.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:27"
    },
    "5": {
      "name": "ENotAllowedMinter",
      "label": "The sender is not on the minter allowlist.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:29"
    },
    "6": {
      "name": "EExceedsAllowance",
      "label": "`amount` exceeds the configured per-call cap.",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/currency/currency_ops.move:31"
    }
  },
  "subou_ops": {
    "0": {
      "name": "EVaultOUMismatch",
      "label": "Vault oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/subou/subou_ops.move:18"
    },
    "1": {
      "name": "ESubOUVaultMismatch",
      "label": "Sub ouvault mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/subou/subou_ops.move:19"
    },
    "3": {
      "name": "EEmptyBatch",
      "label": "Empty batch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/subou/subou_ops.move:20"
    },
    "8": {
      "name": "EBatchTooLarge",
      "label": "Batch too large",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/subou/subou_ops.move:21"
    }
  },
  "treasury_ops": {
    "0": {
      "name": "EVaultOUMismatch",
      "label": "Vault oumismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/treasury/treasury_ops.move:15"
    },
    "1": {
      "name": "ETargetVaultMismatch",
      "label": "Target vault mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/treasury/treasury_ops.move:16"
    },
    "2": {
      "name": "EExceedsDailyCap",
      "label": "Exceeds daily cap",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/treasury/treasury_ops.move:17"
    }
  },
  "upgrade_ops": {
    "0": {
      "name": "EVaultOuMismatch",
      "label": "Vault ou mismatch",
      "message": null,
      "clever": false,
      "source": "armature/packages/armature_proposals/sources/upgrade/upgrade_ops.move:11"
    }
  },
  "keyspace": {
    "0": {
      "name": "ENotAllowed",
      "label": "Not allowed",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:50"
    },
    "1": {
      "name": "EAlreadyGranted",
      "label": "Already granted",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:51"
    },
    "2": {
      "name": "ENotGranted",
      "label": "Not granted",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:52"
    },
    "3": {
      "name": "EAlreadyCurrentEpoch",
      "label": "Already current epoch",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:53"
    },
    "4": {
      "name": "EWrongKeyspace",
      "label": "Wrong keyspace",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:54"
    },
    "5": {
      "name": "ELastGrantor",
      "label": "Last grantor",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:55"
    },
    "6": {
      "name": "ELastWriter",
      "label": "Last writer",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:56"
    },
    "7": {
      "name": "ELastReader",
      "label": "Last reader",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:57"
    },
    "8": {
      "name": "EEmptyGrantPrincipals",
      "label": "Empty grant principals",
      "message": null,
      "clever": false,
      "source": "armature-vault/packages/armature_vault/sources/keyspace/keyspace.move:58"
    }
  },
  "ou_receipt_vault": {
    "0": {
      "name": "ENotAuthorized",
      "label": "Not authorized",
      "message": "Sender does not satisfy any principal for the required role",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:67"
    },
    "1": {
      "name": "EInsufficientVaultBalance",
      "label": "Insufficient vault balance",
      "message": "Insufficient balance in the receipt vault",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:70"
    },
    "2": {
      "name": "EWrongCollection",
      "label": "Wrong collection",
      "message": "Receipt collection_id does not match this vault's collection",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:72"
    },
    "3": {
      "name": "EVaultAlreadyExists",
      "label": "Vault already exists",
      "message": "A receipt vault already exists for this OU at this storage unit",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:75"
    },
    "4": {
      "name": "ELastEditor",
      "label": "Last editor",
      "message": "Cannot remove the last Edit principal — the vault would be unadministrable",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:78"
    },
    "5": {
      "name": "EInvalidArguments",
      "label": "Invalid arguments",
      "message": "Invalid arguments (e.g. parallel vectors of different lengths)",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:81"
    },
    "6": {
      "name": "EZeroAmount",
      "label": "Zero amount",
      "message": "Amount must be greater than zero",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:84"
    },
    "7": {
      "name": "EEditorWouldLockSelf",
      "label": "Editor would lock self",
      "message": "Revocation would leave the caller unable to administer the vault",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:86"
    },
    "8": {
      "name": "EVaultNonEmpty",
      "label": "Vault non empty",
      "message": "Vault holds at least one non-empty asset balance — drain before deinit",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:89"
    },
    "9": {
      "name": "EVaultRegistryMismatch",
      "label": "Vault registry mismatch",
      "message": "Registry slot does not point at this vault",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:92"
    },
    "10": {
      "name": "EStorageUnitMismatch",
      "label": "Storage unit mismatch",
      "message": "VaultConfig does not bind the passed StorageUnit",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:94"
    },
    "11": {
      "name": "EEmptyEditPrincipals",
      "label": "Empty edit principals",
      "message": "edit_principals must be non-empty — vault would have no administrator",
      "clever": true,
      "source": "armature-vault/packages/armature_vault/sources/receipt_vault/ou_receipt_vault.move:96"
    }
  },
  "trading_ops": {
    "0": {
      "name": "EWrongTradingAccount",
      "label": "Wrong trading account",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:48"
    },
    "1": {
      "name": "EWrongCustody",
      "label": "Wrong custody",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:49"
    },
    "2": {
      "name": "EWrongVault",
      "label": "Wrong vault",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:50"
    },
    "3": {
      "name": "EWrongPool",
      "label": "Wrong pool",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:51"
    },
    "4": {
      "name": "EWrongOu",
      "label": "Wrong ou",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:52"
    },
    "5": {
      "name": "EWrongTreasury",
      "label": "Wrong treasury",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:53"
    },
    "6": {
      "name": "EWrongCollection",
      "label": "Wrong collection",
      "message": null,
      "clever": false,
      "source": "armature-trading/packages/armature_trading/sources/trading_ops.move:54"
    }
  }
}
