// Generated by scripts/generate-error-codes.mjs — do not edit by hand.
// Source: loash-industries/trinary-exchange @ packages/triex/sources, packages/token/sources
// Regenerate: npm run generate:error-codes

/** Every abort constant declared by the contracts, as `module::EConstantName`. */
export type MoveAbortName =
  | 'book::EInvalidAmountIn'
  | 'book::EEmptyOrderbook'
  | 'book::EInvalidPriceRange'
  | 'book::EInvalidTicks'
  | 'book::ENewQuantityMustBeLessThanOriginal'
  | 'order::EInvalidNewQuantity'
  | 'order::EOrderExpired'
  | 'order::EMakerFeeRateTooWide'
  | 'order::ECancelRetentionTooWide'
  | 'order::EOrderBelowMinimumSize'
  | 'order_info::EOrderInvalidPrice'
  | 'order_info::EOrderBelowMinimumSize'
  | 'order_info::EInvalidExpireTimestamp'
  | 'order_info::EInvalidOrderType'
  | 'order_info::EPOSTOrderCrossesOrderbook'
  | 'order_info::EFOKOrderCannotBeFullyFilled'
  | 'order_info::EMarketOrderCannotBePostOnly'
  | 'order_info::ESelfMatchingCancelTaker'
  | 'fee_policy::EClassAlreadyExists'
  | 'fee_policy::EClassDoesNotExist'
  | 'fee_policy::EInvalidCancelRetention'
  | 'fee_policy::ENoDefaultClassForQuote'
  | 'fee_policy::EClassQuoteMismatch'
  | 'fee_policy::EDuplicateGenesisClass'
  | 'fee_policy::EInvalidQuoteUnit'
  | 'fee_policy::EOperatorShareAboveCeiling'
  | 'fee_policy::EOperatorShareClassDoesNotExist'
  | 'fee_policy::ENoAuthorizedAdapter'
  | 'fee_policy::EUnauthorizedAdapter'
  | 'fee_policy::EAdapterPinned'
  | 'big_vector::ESliceTooSmall'
  | 'big_vector::ESliceTooBig'
  | 'big_vector::EFanOutTooSmall'
  | 'big_vector::EFanOutTooBig'
  | 'big_vector::ENotEmpty'
  | 'big_vector::ENotFound'
  | 'big_vector::EExists'
  | 'big_vector::EBadRemove'
  | 'big_vector::ENotAdjacent'
  | 'big_vector::EBadRedistribution'
  | 'constants::EOrderInfoMismatch'
  | 'constants::EBookOrderMismatch'
  | 'constants::EIncorrectPoolId'
  | 'constants::EFillMismatch'
  | 'math::EInvalidPrecision'
  | 'math::EOverflow'
  | 'multicoin_pool::EInvalidFee'
  | 'multicoin_pool::EInvalidQuantityIn'
  | 'multicoin_pool::EInvalidOrderTradingAccount'
  | 'multicoin_pool::EPackageVersionDisabled'
  | 'multicoin_pool::EMinimumQuantityOutNotMet'
  | 'multicoin_pool::EPoolNotRegistered'
  | 'multicoin_pool::EQuoteNotApproved'
  | 'multicoin_pool::ENoOperatorBeneficiary'
  | 'pool::EInvalidFee'
  | 'pool::ESameBaseAndQuote'
  | 'pool::EInvalidQuantityIn'
  | 'pool::EInvalidOrderTradingAccount'
  | 'pool::EPackageVersionDisabled'
  | 'pool::EMinimumQuantityOutNotMet'
  | 'pool::EPoolNotRegistered'
  | 'pool::EQuoteNotApproved'
  | 'pool::EInvalidDecimalPair'
  | 'registry::EPoolAlreadyExists'
  | 'registry::EPoolDoesNotExist'
  | 'registry::EPackageVersionNotEnabled'
  | 'registry::EVersionNotEnabled'
  | 'registry::EVersionAlreadyEnabled'
  | 'registry::EMaxTradingAccountsReached'
  | 'registry::EQuoteNotApproved'
  | 'registry::EQuoteAlreadyApproved'
  | 'registry::EMulticoinPoolAlreadyExists'
  | 'registry::EMulticoinPoolDoesNotExist'
  | 'registry::EQuoteInsufficientDecimals'
  | 'fee_schedule::EEmptySchedule'
  | 'fee_schedule::EFirstTierNotZero'
  | 'fee_schedule::EThresholdsNotAscending'
  | 'fee_schedule::ETakerRateNotMonotone'
  | 'fee_schedule::EMakerRateNotMonotone'
  | 'fee_schedule::ETooManyTiers'
  | 'fee_schedule::EInvalidTakerFee'
  | 'fee_schedule::EInvalidMakerFee'
  | 'fee_schedule::EVectorLengthMismatch'
  | 'fee_turnover::EEpochAhead'
  | 'state::EMaxOpenOrders'
  | 'trading_account::EInvalidOwner'
  | 'trading_account::EInvalidTrader'
  | 'trading_account::EInvalidProof'
  | 'trading_account::ETradingAccountBalanceTooLow'
  | 'trading_account::EMaxCapsReached'
  | 'trading_account::ECapNotInList'
  | 'trading_account::EMultiCoinBalanceTooLow'
  | 'coin_vault::EInsufficientFeeReserve'
  | 'coin_vault::EFeesLocked'
  | 'coin_vault::ENoBalanceToSettle'
  | 'coin_vault::EHasOwedBalances'
  | 'multicoin_vault::EInsufficientBaseBalance'
  | 'multicoin_vault::EInsufficientQuoteBalance'
  | 'multicoin_vault::EInsufficientCredBalance'
  | 'multicoin_vault::EInsufficientFeeReserve'
  | 'multicoin_vault::EFeesLocked'
  | 'multicoin_vault::ENoBalanceToSettle'
  | 'multicoin_vault::EHasOwedBalances'
  | 'multicoin_vault::EOperatorShareAboveCeiling'

export interface MoveAbortEntry {
  /** The Move constant's name, e.g. `EInvalidFee`. */
  name: string
  /** Label derived from the constant's doc comment, or from its name. */
  label: string
  /** The `#[error]` message string, when the constant declares one. */
  message: string | null
  /** Whether the constant is a clever error (`#[error(code = N)]`). */
  clever: boolean
  /** Where the constant is declared, for debugging. */
  source: string
}

/** Abort entries keyed by module name, then by abort code. */
export const MOVE_ABORT_CATALOG: Record<
  string,
  Record<number, MoveAbortEntry>
> = {
  "book": {
    "1": {
      "name": "EInvalidAmountIn",
      "label": "Invalid amount in",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:45"
    },
    "2": {
      "name": "EEmptyOrderbook",
      "label": "Empty orderbook",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:46"
    },
    "3": {
      "name": "EInvalidPriceRange",
      "label": "Invalid price range",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:47"
    },
    "4": {
      "name": "EInvalidTicks",
      "label": "Invalid ticks",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:48"
    },
    "7": {
      "name": "ENewQuantityMustBeLessThanOriginal",
      "label": "New quantity must be less than original",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/book.move:49"
    }
  },
  "order": {
    "0": {
      "name": "EInvalidNewQuantity",
      "label": "Invalid new quantity",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:8"
    },
    "1": {
      "name": "EOrderExpired",
      "label": "Order expired",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:9"
    },
    "2": {
      "name": "EMakerFeeRateTooWide",
      "label": "A snapshotted rate was out of range, or finer than the whole basis point the order stores. The real bounds are enforced where the rates are set, in `triex::fee_policy`; these are the backstop that keeps the encoding total.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:13"
    },
    "3": {
      "name": "ECancelRetentionTooWide",
      "label": "Cancel retention too wide",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:14"
    },
    "4": {
      "name": "EOrderBelowMinimumSize",
      "label": "Order below minimum size",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order.move:15"
    }
  },
  "order_info": {
    "0": {
      "name": "EOrderInvalidPrice",
      "label": "Order invalid price",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:18"
    },
    "1": {
      "name": "EOrderBelowMinimumSize",
      "label": "Bound derived from the order's own price rather than a per-pool constant.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:20"
    },
    "3": {
      "name": "EInvalidExpireTimestamp",
      "label": "Invalid expire timestamp",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:21"
    },
    "4": {
      "name": "EInvalidOrderType",
      "label": "Invalid order type",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:22"
    },
    "5": {
      "name": "EPOSTOrderCrossesOrderbook",
      "label": "POSTOrder crosses orderbook",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:23"
    },
    "6": {
      "name": "EFOKOrderCannotBeFullyFilled",
      "label": "FOKOrder cannot be fully filled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:24"
    },
    "7": {
      "name": "EMarketOrderCannotBePostOnly",
      "label": "Market order cannot be post only",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:25"
    },
    "8": {
      "name": "ESelfMatchingCancelTaker",
      "label": "Self matching cancel taker",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/book/order_info.move:26"
    }
  },
  "fee_policy": {
    "0": {
      "name": "EClassAlreadyExists",
      "label": "Class already exists",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:26"
    },
    "1": {
      "name": "EClassDoesNotExist",
      "label": "Class does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:27"
    },
    "2": {
      "name": "EInvalidCancelRetention",
      "label": "Invalid cancel retention",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:28"
    },
    "3": {
      "name": "ENoDefaultClassForQuote",
      "label": "No default class for quote",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:29"
    },
    "4": {
      "name": "EClassQuoteMismatch",
      "label": "Class quote mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:30"
    },
    "5": {
      "name": "EDuplicateGenesisClass",
      "label": "Duplicate genesis class",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:31"
    },
    "6": {
      "name": "EInvalidQuoteUnit",
      "label": "Invalid quote unit",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:32"
    },
    "7": {
      "name": "EOperatorShareAboveCeiling",
      "label": "Operator share above ceiling",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:33"
    },
    "8": {
      "name": "EOperatorShareClassDoesNotExist",
      "label": "Operator share class does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:34"
    },
    "9": {
      "name": "ENoAuthorizedAdapter",
      "label": "No authorized adapter",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:35"
    },
    "10": {
      "name": "EUnauthorizedAdapter",
      "label": "Unauthorized adapter",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:36"
    },
    "11": {
      "name": "EAdapterPinned",
      "label": "Adapter pinned",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/fee_policy.move:37"
    }
  },
  "big_vector": {
    "0": {
      "name": "ESliceTooSmall",
      "label": "Max Slice Size provided is too small.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:79"
    },
    "1": {
      "name": "ESliceTooBig",
      "label": "Max Slice Size provided is too big.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:82"
    },
    "2": {
      "name": "EFanOutTooSmall",
      "label": "Max Fan-out provided is too small.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:85"
    },
    "3": {
      "name": "EFanOutTooBig",
      "label": "Max Fan-out provided is too big.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:88"
    },
    "4": {
      "name": "ENotEmpty",
      "label": "`BigVector` is not empty.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:91"
    },
    "5": {
      "name": "ENotFound",
      "label": "Key not found in `BigVector`.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:94"
    },
    "6": {
      "name": "EExists",
      "label": "Key already exists in `BigVector`.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:97"
    },
    "7": {
      "name": "EBadRemove",
      "label": "Found a node in an unexpected state during removal (namely, we tried to remove from a node's child and found that it had become empty, which should not be possible).",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:102"
    },
    "8": {
      "name": "ENotAdjacent",
      "label": "Found a pair of nodes that are expected to be adjacent but whose linked list pointers don't match up.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:106"
    },
    "9": {
      "name": "EBadRedistribution",
      "label": "Tried to redistribute between two nodes, but the operation would have had no effect.",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/big_vector.move:110"
    }
  },
  "constants": {
    "0": {
      "name": "EOrderInfoMismatch",
      "label": "Order info mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:100"
    },
    "1": {
      "name": "EBookOrderMismatch",
      "label": "Book order mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:102"
    },
    "3": {
      "name": "EIncorrectPoolId",
      "label": "Incorrect pool id",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:104"
    },
    "4": {
      "name": "EFillMismatch",
      "label": "Fill mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/constants.move:106"
    }
  },
  "math": {
    "0": {
      "name": "EInvalidPrecision",
      "label": "Error codes",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/math.move:8"
    },
    "1": {
      "name": "EOverflow",
      "label": "Overflow",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/helper/math.move:9"
    }
  },
  "multicoin_pool": {
    "1": {
      "name": "EInvalidFee",
      "label": "Invalid fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:34"
    },
    "8": {
      "name": "EInvalidQuantityIn",
      "label": "Invalid quantity in",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:35"
    },
    "9": {
      "name": "EInvalidOrderTradingAccount",
      "label": "Invalid order trading account",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:36"
    },
    "11": {
      "name": "EPackageVersionDisabled",
      "label": "Package version disabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:37"
    },
    "13": {
      "name": "EMinimumQuantityOutNotMet",
      "label": "Minimum quantity out not met",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:38"
    },
    "14": {
      "name": "EPoolNotRegistered",
      "label": "Pool not registered",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:39"
    },
    "20": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:40"
    },
    "21": {
      "name": "ENoOperatorBeneficiary",
      "label": "No operator beneficiary",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/multicoin_pool.move:41"
    }
  },
  "pool": {
    "1": {
      "name": "EInvalidFee",
      "label": "Invalid fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:35"
    },
    "2": {
      "name": "ESameBaseAndQuote",
      "label": "Same base and quote",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:36"
    },
    "6": {
      "name": "EInvalidQuantityIn",
      "label": "Invalid quantity in",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:37"
    },
    "9": {
      "name": "EInvalidOrderTradingAccount",
      "label": "Invalid order trading account",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:38"
    },
    "11": {
      "name": "EPackageVersionDisabled",
      "label": "Package version disabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:39"
    },
    "12": {
      "name": "EMinimumQuantityOutNotMet",
      "label": "Minimum quantity out not met",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:40"
    },
    "14": {
      "name": "EPoolNotRegistered",
      "label": "Pool not registered",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:42"
    },
    "20": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:47"
    },
    "21": {
      "name": "EInvalidDecimalPair",
      "label": "Invalid decimal pair",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/pool.move:48"
    }
  },
  "registry": {
    "1": {
      "name": "EPoolAlreadyExists",
      "label": "Pool already exists",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:15"
    },
    "2": {
      "name": "EPoolDoesNotExist",
      "label": "Pool does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:16"
    },
    "3": {
      "name": "EPackageVersionNotEnabled",
      "label": "Package version not enabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:17"
    },
    "4": {
      "name": "EVersionNotEnabled",
      "label": "Version not enabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:18"
    },
    "5": {
      "name": "EVersionAlreadyEnabled",
      "label": "Version already enabled",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:19"
    },
    "9": {
      "name": "EMaxTradingAccountsReached",
      "label": "Max trading accounts reached",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:23"
    },
    "10": {
      "name": "EQuoteNotApproved",
      "label": "Quote not approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:24"
    },
    "11": {
      "name": "EQuoteAlreadyApproved",
      "label": "Quote already approved",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:25"
    },
    "13": {
      "name": "EMulticoinPoolAlreadyExists",
      "label": "Multicoin pool already exists",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:26"
    },
    "14": {
      "name": "EMulticoinPoolDoesNotExist",
      "label": "Multicoin pool does not exist",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:27"
    },
    "15": {
      "name": "EQuoteInsufficientDecimals",
      "label": "Quote insufficient decimals",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/registry.move:28"
    }
  },
  "fee_schedule": {
    "0": {
      "name": "EEmptySchedule",
      "label": "Empty schedule",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:16"
    },
    "1": {
      "name": "EFirstTierNotZero",
      "label": "First tier not zero",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:17"
    },
    "2": {
      "name": "EThresholdsNotAscending",
      "label": "Thresholds not ascending",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:18"
    },
    "3": {
      "name": "ETakerRateNotMonotone",
      "label": "Taker rate not monotone",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:19"
    },
    "4": {
      "name": "EMakerRateNotMonotone",
      "label": "Maker rate not monotone",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:20"
    },
    "5": {
      "name": "ETooManyTiers",
      "label": "Too many tiers",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:21"
    },
    "6": {
      "name": "EInvalidTakerFee",
      "label": "Invalid taker fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:22"
    },
    "7": {
      "name": "EInvalidMakerFee",
      "label": "Invalid maker fee",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:23"
    },
    "8": {
      "name": "EVectorLengthMismatch",
      "label": "Vector length mismatch",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_schedule.move:24"
    }
  },
  "fee_turnover": {
    "0": {
      "name": "EEpochAhead",
      "label": "Epoch ahead",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/fee_turnover.move:20"
    }
  },
  "state": {
    "2": {
      "name": "EMaxOpenOrders",
      "label": "Max open orders",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/state/state.move:20"
    }
  },
  "trading_account": {
    "0": {
      "name": "EInvalidOwner",
      "label": "Invalid owner",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:26"
    },
    "1": {
      "name": "EInvalidTrader",
      "label": "Invalid trader",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:27"
    },
    "2": {
      "name": "EInvalidProof",
      "label": "Invalid proof",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:28"
    },
    "3": {
      "name": "ETradingAccountBalanceTooLow",
      "label": "Trading account balance too low",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:29"
    },
    "4": {
      "name": "EMaxCapsReached",
      "label": "Max caps reached",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:30"
    },
    "5": {
      "name": "ECapNotInList",
      "label": "Cap not in list",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:31"
    },
    "7": {
      "name": "EMultiCoinBalanceTooLow",
      "label": "Multi coin balance too low",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/trading_account.move:34"
    }
  },
  "coin_vault": {
    "0": {
      "name": "EInsufficientFeeReserve",
      "label": "Insufficient fee reserve",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/coin_vault.move:19"
    },
    "1": {
      "name": "EFeesLocked",
      "label": "Fees locked",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/coin_vault.move:20"
    },
    "7": {
      "name": "ENoBalanceToSettle",
      "label": "No balance to settle",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/coin_vault.move:21"
    },
    "8": {
      "name": "EHasOwedBalances",
      "label": "Has owed balances",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/coin_vault.move:22"
    }
  },
  "multicoin_vault": {
    "1": {
      "name": "EInsufficientBaseBalance",
      "label": "Insufficient base balance",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:18"
    },
    "2": {
      "name": "EInsufficientQuoteBalance",
      "label": "Insufficient quote balance",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:19"
    },
    "3": {
      "name": "EInsufficientCredBalance",
      "label": "Insufficient cred balance",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:20"
    },
    "5": {
      "name": "EInsufficientFeeReserve",
      "label": "Insufficient fee reserve",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:21"
    },
    "6": {
      "name": "EFeesLocked",
      "label": "Fees locked",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:22"
    },
    "7": {
      "name": "ENoBalanceToSettle",
      "label": "No balance to settle",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:23"
    },
    "8": {
      "name": "EHasOwedBalances",
      "label": "Has owed balances",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:24"
    },
    "9": {
      "name": "EOperatorShareAboveCeiling",
      "label": "Operator share above ceiling",
      "message": null,
      "clever": false,
      "source": "packages/triex/sources/vault/multicoin_vault.move:25"
    }
  }
}
